[package]
name = "openapi"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.8"
axum-server = "0.8.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mongodb = "3.5.1"
futures = "0.3"
dotenv = "0.15"
async-trait = "0.1"
uuid = { version = "1.21", features = ["v4"] }
mime_guess = "2.0"
regex = "1"
htmlescape = "0.3"
anyhow = "1.0"

[dev-dependencies]
reqwest = { version = "0.13", features = ["json"] }
tokio-test = "0.4"
tower = "0.5"
